import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    en: {
        title: 'Yalla Breakfast',
        subtitle: 'Track food expenses by employee',
        addFoodItems: 'Add Food Items',
        employees: 'Employees',
        selectEmployee: 'Select Employee...',
        foodItems: 'Food Items',
        foodItemName: 'Food Item Name',
        quantity: 'Quantity',
        price: 'Price',
        addItem: 'Add Item',
        removeItem: 'Remove Item',
        save: 'Save',
        cancel: 'Cancel',
        edit: 'Edit',
        delete: 'Delete',
        total: 'Total',
        employeeTotals: 'Employee Totals',
        grandTotal: 'Grand Total',
        noData: 'No data available',
        analytics: 'Analytics',
        employeeCostAnalysis: 'Employee Cost Analysis',
        totalOrders: 'Total Orders',
        averageOrderValue: 'Average Order Value',
        mostExpensiveOrder: 'Most Expensive Order',
        cheapestOrder: 'Cheapest Order',
        orderFrequency: 'Order Frequency',
        itemPriceComparison: 'Item Price Comparison',
        monthlyTrends: 'Monthly Trends',
        exportData: 'Export Data',
        importData: 'Import Data',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        language: 'Language',
        bulkDelete: 'Bulk Delete',
        selectAll: 'Select All',
        totalAmount: 'Total Amount',
        totalItems: 'Total Items',
        orderCount: 'Order Count',
        avgOrderValue: 'Avg Order Value',
        avgItemPrice: 'Avg Item Price',
        orderHistory: 'Order History',
        qty: 'Qty',
        settings: 'Settings',
        backToHome: 'Back to Home',
        dataStorageManagement: 'Data Storage Management',
        storageUsage: 'Storage Usage',
        totalSize: 'Total Size',
        storageFoodItems: 'Food Items',
        storageBackups: 'Backups',
        showInfo: 'Show Info',
        hideInfo: 'Hide Info',
        exportImport: 'Export/Import',
        storageExportData: 'Export Data',
        storageImportData: 'Import Data',
        importing: 'Importing...',
        createBackup: 'Create Backup',
        clearAllData: 'Clear All Data',
        availableBackups: 'Available Backups',
        storageItems: 'Items',
        restore: 'Restore',
        storageDelete: 'Delete',
        storageOverview: 'Storage Overview',
        totalDataStored: 'Total Data Stored',
        totalItems: 'Total Items',
        totalBackups: 'Total Backups',
        backupManagement: 'Backup Management',
        backupDescription: 'Create and manage backup copies',
        dataHistory: 'Data History',
        dataHistoryDescription: 'View detailed information about your data',
        showDetails: 'Show Details',
        hideDetails: 'Hide Details',
        manageDataAndBackups: 'Manage your data and create backups',
        // Order Form
        orderDetails: 'Order Details',
        editOrder: 'Edit Order',
        createNewOrder: 'Create New Order',
        orderName: 'Order Name',
        orderNamePlaceholder: 'e.g., Lunch Order - Restaurant Name',
        deliveryFee: 'Delivery Fee',
        products: 'Products',
        addEmployeeToOrder: 'Add Employee to Order',
        selectEmployee: 'Select Employee',
        productRows: 'Products',
        addProduct: 'Add Product',
        productName: 'Product name',
        qty: 'Qty',
        price: 'Price',
        orderSummary: 'Order Summary',
        subtotal: 'Subtotal (Food)',
        deliveryFeePerPerson: 'Delivery Fee Per Person',
        totalOrderAmount: 'Total Order Amount',
        employeeBreakdown: 'Employee Breakdown',
        food: 'Food',
        delivery: 'Delivery',
        updateOrder: 'Update Order',
        createOrder: 'Create Order',
        clearForm: 'Clear Form',
        pleaseAddEmployeeWithProducts: 'Please add at least one employee with products.',
        // Order List
        orders: 'Orders',
        newOrder: 'New Order',
        noOrdersYet: 'No orders yet. Create your first order!',
        viewDetails: 'View Details',
        editOrderTooltip: 'Edit Order',
        deleteOrderTooltip: 'Delete Order',
        employee: 'Employee',
        product: 'Product',
        quantity: 'Quantity',
        total: 'Total',
        // Employee Totals
        employeeStatistics: 'Employee Statistics',
        hideDetailedStats: 'Hide Detailed Stats',
        showDetailedStats: 'Show Detailed Stats',
        noEmployeeTotals: 'No employee totals to display',
        // Modern Header
        employeesNav: 'Employees',
        // Modal
        areYouSureDelete: 'Are you sure you want to delete this item? This action cannot be undone.',
        areYouSureDeleteMultiple: 'Are you sure you want to delete {count} items? This action cannot be undone.',
        delete: 'Delete',
        cancel: 'Cancel',
        // Employee Manager
        employeeManagement: 'Employee Management',
        addAndManageTeam: 'Add and manage your team members',
        totalEmployees: 'Total Employees',
        welcomeLetsSetupTeam: 'Welcome! Let\'s set up your team',
        startByAddingEmployees: 'Start by adding your employees. You can add as many as you need, then proceed to create orders.',
        gotIt: 'Got it!',
        searchEmployees: 'Search employees...',
        addEmployee: 'Add Employee',
        addNewEmployee: 'Add New Employee',
        enterEmployeeName: 'Enter employee name',
        pressEnterToAdd: 'Press Enter to add quickly',
        remove: 'Remove',
        noEmployeesFound: 'No employees found',
        tryAdjustingSearch: 'Try adjusting your search',
        addFirstEmployee: 'Add First Employee',
        employeeNameHeader: 'Employee Name',
        addedDate: 'Added Date',
        actionsHeader: 'Actions',
        readyToCreateOrders: 'Ready to create orders?',
        employeesInTeam: 'You have {count} employee{plural} in your team',
        proceedToOrders: 'Proceed to Orders',
        pleaseEnterEmployeeName: 'Please enter an employee name',
        employeeAlreadyExists: 'This employee already exists',
        employeeAddedSuccessfully: 'Employee "{name}" added successfully',
        employeeRemoved: 'Employee "{name}" removed',
        pleaseAddAtLeastOneEmployee: 'Please add at least one employee before proceeding',
        // Analytics
        employeeCosts: 'Employee Costs',
        costDistribution: 'Cost Distribution',
        ordersItemsComparison: 'Orders & Items Comparison',
        averageValuesComparison: 'Average Values Comparison',
        cumulativeCostTrend: 'Cumulative Cost Trend',
        detailedEmployeeStatistics: 'Detailed Employee Statistics',
        totalAmount: 'Total Amount',
        totalItems: 'Total Items',
        ordersCount: 'Orders',
        avgOrder: 'Avg Order',
        avgItem: 'Avg Item',
        totalCost: 'Total Cost',
        numberOfOrders: 'Number of Orders',
        avgOrderValue: 'Avg Order Value',
        avgItemPrice: 'Avg Item Price',
        cost: 'Cost',
        // App
        failedToSaveOrder: 'Failed to save order: ',
        unknown: 'Unknown',
        // Storage Manager
        dataExportedSuccessfully: 'Data exported successfully!',
        dataImportedSuccessfully: 'Data imported successfully!',
        invalidDataFormat: 'Invalid data format!',
        failedToImportFile: 'Failed to import file: ',
        backupCreatedSuccessfully: 'Backup created successfully!',
        backupRestoredSuccessfully: 'Backup restored successfully!',
        failedToRestoreBackup: 'Failed to restore backup!',
        backupDeletedSuccessfully: 'Backup deleted successfully!',
        areYouSureRestoreBackup: 'Are you sure you want to restore this backup? Current data will be replaced.',
        areYouSureDeleteBackup: 'Are you sure you want to delete this backup?',
        areYouSureClearAllData: 'Are you sure you want to clear all data? This action cannot be undone.',
        hide: 'Hide',
        show: 'Show',
        info: 'Info',
        storageUsage: 'Storage Usage',
        totalSize: 'Total Size',
        foodItems: 'Food Items',
        backups: 'Backups',
        exportImport: 'Export/Import',
        storageExportData: 'Export Data',
        storageImportData: 'Import Data',
        importing: 'Importing...',
        backupManagement: 'Backup Management',
        createBackup: 'Create Backup',
        clearAllData: 'Clear All Data',
        availableBackups: 'Available Backups',
        storageItems: 'Items',
        restore: 'Restore',
        storageDelete: 'Delete',
        items: 'Items'
    },
    ar: {
        title: 'يلا فطور ',
        subtitle: 'تتبع مصاريف الطعام حسب الموظف',
        addFoodItems: 'إضافة عناصر الطعام',
        employees: 'الموظفين',
        selectEmployee: 'اختر الموظف...',
        foodItems: 'عناصر الطعام',
        foodItemName: 'اسم عنصر الطعام',
        quantity: 'الكمية',
        price: 'السعر',
        addItem: 'إضافة عنصر',
        removeItem: 'إزالة عنصر',
        save: 'حفظ',
        cancel: 'إلغاء',
        edit: 'تعديل',
        delete: 'حذف',
        total: 'الإجمالي',
        employeeTotals: 'إجماليات الموظفين',
        grandTotal: 'المجموع الكلي',
        noData: 'لا توجد بيانات',
        analytics: 'التحليلات',
        employeeCostAnalysis: 'تحليل تكاليف الموظفين',
        totalOrders: 'إجمالي الطلبات',
        averageOrderValue: 'متوسط قيمة الطلب',
        mostExpensiveOrder: 'أغلى طلب',
        cheapestOrder: 'أرخص طلب',
        orderFrequency: 'تكرار الطلبات',
        itemPriceComparison: 'مقارنة أسعار العناصر',
        monthlyTrends: 'الاتجاهات الشهرية',
        exportData: 'تصدير البيانات',
        importData: 'استيراد البيانات',
        darkMode: 'الوضع الليلي',
        lightMode: 'الوضع النهاري',
        language: 'اللغة',
        bulkDelete: 'حذف متعدد',
        selectAll: 'تحديد الكل',
        totalAmount: 'المبلغ الإجمالي',
        totalItems: 'إجمالي العناصر',
        orderCount: 'عدد الطلبات',
        avgOrderValue: 'متوسط قيمة الطلب',
        avgItemPrice: 'متوسط سعر العنصر',
        orderHistory: 'سجل الطلبات',
        qty: 'كمية',
        settings: 'الإعدادات',
        backToHome: 'العودة للرئيسية',
        dataStorageManagement: 'إدارة تخزين البيانات',
        storageUsage: 'استخدام التخزين',
        totalSize: 'الحجم الكلي',
        storageFoodItems: 'عناصر الطعام',
        storageBackups: 'النسخ الاحتياطية',
        showInfo: 'عرض المعلومات',
        hideInfo: 'إخفاء المعلومات',
        exportImport: 'تصدير/استيراد',
        storageExportData: 'تصدير البيانات',
        storageImportData: 'استيراد البيانات',
        importing: 'جاري الاستيراد...',
        createBackup: 'إنشاء نسخة احتياطية',
        clearAllData: 'حذف جميع البيانات',
        availableBackups: 'النسخ الاحتياطية المتاحة',
        storageItems: 'العناصر',
        restore: 'استعادة',
        storageDelete: 'حذف',
        storageOverview: 'نظرة عامة على التخزين',
        totalDataStored: 'إجمالي البيانات المخزنة',
        totalItems: 'إجمالي العناصر',
        totalBackups: 'إجمالي النسخ',
        backupManagement: 'إدارة النسخ الاحتياطية',
        backupDescription: 'إنشاء وإدارة نسخ احتياطية',
        dataHistory: 'سجل البيانات',
        dataHistoryDescription: 'عرض معلومات مفصلة حول بياناتك',
        showDetails: 'عرض التفاصيل',
        hideDetails: 'إخفاء التفاصيل',
        manageDataAndBackups: 'إدارة بياناتك وإنشاء نسخ احتياطية',
        // Order Form
        orderDetails: 'تفاصيل الطلب',
        editOrder: 'تعديل الطلب',
        createNewOrder: 'إنشاء طلب جديد',
        orderName: 'اسم الطلب',
        orderNamePlaceholder: 'مثال: طلب الغداء - اسم المطعم',
        deliveryFee: 'رسوم التوصيل',
        products: 'المنتجات',
        addEmployeeToOrder: 'إضافة موظف للطلب',
        selectEmployee: 'اختر الموظف',
        productRows: 'المنتجات',
        addProduct: 'إضافة منتج',
        productName: 'اسم المنتج',
        qty: 'الكمية',
        price: 'السعر',
        orderSummary: 'ملخص الطلب',
        subtotal: 'المجموع الفرعي (الطعام)',
        deliveryFeePerPerson: 'رسوم التوصيل للشخص',
        totalOrderAmount: 'مجموع الطلب الإجمالي',
        employeeBreakdown: 'تفصيل الموظفين',
        food: 'الطعام',
        delivery: 'التوصيل',
        updateOrder: 'تحديث الطلب',
        createOrder: 'إنشاء طلب',
        clearForm: 'مسح النموذج',
        pleaseAddEmployeeWithProducts: 'يرجى إضافة موظف واحد على الأقل مع المنتجات.',
        // Order List
        orders: 'الطلبات',
        newOrder: 'طلب جديد',
        noOrdersYet: 'لا توجد طلبات بعد. أنشئ طلبك الأول!',
        viewDetails: 'عرض التفاصيل',
        editOrderTooltip: 'تعديل الطلب',
        deleteOrderTooltip: 'حذف الطلب',
        employee: 'الموظف',
        product: 'المنتج',
        quantity: 'الكمية',
        total: 'الإجمالي',
        // Food Table
        selectedItems: 'العناصر المحددة',
        selectAll: 'تحديد الكل',
        clearSelection: 'مسح التحديد',
        employeeName: 'اسم الموظف',
        foodItem: 'عنصر الطعام',
        actions: 'الإجراءات',
        selectRow: 'تحديد الصف',
        noFoodItemsMessage: 'لا توجد عناصر طعام متاحة. ابدأ بإضافة طلبك الأول!',
        addFirstItem: 'إضافة أول عنصر',
        // Employee Totals
        employeeStatistics: 'إحصائيات الموظفين',
        hideDetailedStats: 'إخفاء الإحصائيات التفصيلية',
        showDetailedStats: 'عرض الإحصائيات التفصيلية',
        noEmployeeTotals: 'لا توجد إجماليات موظفين لعرضها',
        // Modern Header
        employeesNav: 'الموظفين',
        // Modal
        areYouSureDelete: 'هل أنت متأكد من حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.',
        areYouSureDeleteMultiple: 'هل أنت متأكد من حذف {count} عناصر؟ لا يمكن التراجع عن هذا الإجراء.',
        delete: 'حذف',
        cancel: 'إلغاء',
        // Employee Manager
        employeeManagement: 'إدارة الموظفين',
        addAndManageTeam: 'إضافة وإدارة أعضاء فريقك',
        totalEmployees: 'إجمالي الموظفين',
        welcomeLetsSetupTeam: 'مرحباً! لنجهز فريقك',
        startByAddingEmployees: 'ابدأ بإضافة موظفيك. يمكنك إضافة العدد الذي تريده، ثم المضي قدماً في إنشاء الطلبات.',
        gotIt: 'فهمت!',
        searchEmployees: 'البحث عن الموظفين...',
        addEmployee: 'إضافة موظف',
        addNewEmployee: 'إضافة موظف جديد',
        enterEmployeeName: 'أدخل اسم الموظف',
        pressEnterToAdd: 'اضغط Enter للإضافة بسرعة',
        remove: 'إزالة',
        noEmployeesFound: 'لم يتم العثور على موظفين',
        tryAdjustingSearch: 'حاول تعديل البحث',
        addFirstEmployee: 'إضافة أول موظف',
        employeeNameHeader: 'اسم الموظف',
        addedDate: 'تاريخ الإضافة',
        actionsHeader: 'الإجراءات',
        readyToCreateOrders: 'هل أنت مستعد لإنشاء الطلبات؟',
        employeesInTeam: 'لديك {count} موظف{plural} في فريقك',
        proceedToOrders: 'المضي قدماً للطلبات',
        pleaseEnterEmployeeName: 'يرجى إدخال اسم الموظف',
        employeeAlreadyExists: 'هذا الموظف موجود بالفعل',
        employeeAddedSuccessfully: 'تمت إضافة الموظف "{name}" بنجاح',
        employeeRemoved: 'تمت إزالة الموظف "{name}"',
        pleaseAddAtLeastOneEmployee: 'يرجى إضافة موظف واحد على الأقل قبل المضي قدماً',
        // Analytics
        employeeCosts: 'تكاليف الموظفين',
        costDistribution: 'توزيع التكاليف',
        ordersItemsComparison: 'مقارنة الطلبات والعناصر',
        averageValuesComparison: 'مقارنة القيم المتوسطة',
        cumulativeCostTrend: 'اتجاه التكلفة التراكمي',
        detailedEmployeeStatistics: 'إحصائيات الموظفين التفصيلية',
        totalAmount: 'المبلغ الإجمالي',
        totalItems: 'إجمالي العناصر',
        ordersCount: 'الطلبات',
        avgOrder: 'متوسط الطلب',
        avgItem: 'متوسط العنصر',
        totalCost: 'التكلفة الإجمالية',
        numberOfOrders: 'عدد الطلبات',
        avgOrderValue: 'متوسط قيمة الطلب',
        avgItemPrice: 'متوسط سعر العنصر',
        cost: 'التكلفة',
        // App
        failedToSaveOrder: 'فشل في حفظ الطلب: ',
        unknown: 'غير معروف',
        // Storage Manager
        dataExportedSuccessfully: 'تم تصدير البيانات بنجاح!',
        dataImportedSuccessfully: 'تم استيراد البيانات بنجاح!',
        invalidDataFormat: 'تنسيق البيانات غير صالح!',
        failedToImportFile: 'فشل في استيراد الملف: ',
        backupCreatedSuccessfully: 'تم إنشاء النسخة الاحتياطية بنجاح!',
        backupRestoredSuccessfully: 'تم استعادة النسخة الاحتياطية بنجاح!',
        failedToRestoreBackup: 'فشل في استعادة النسخة الاحتياطية!',
        backupDeletedSuccessfully: 'تم حذف النسخة الاحتياطية بنجاح!',
        areYouSureRestoreBackup: 'هل أنت متأكد من استعادة هذه النسخة الاحتياطية؟ سيتم استبدال البيانات الحالية.',
        areYouSureDeleteBackup: 'هل أنت متأكد من حذف هذه النسخة الاحتياطية؟',
        areYouSureClearAllData: 'هل أنت متأكد من مسح جميع البيانات؟ لا يمكن التراجع عن هذا الإجراء.',
        hide: 'إخفاء',
        show: 'عرض',
        info: 'معلومات',
        storageUsage: 'استخدام التخزين',
        totalSize: 'الحجم الكلي',
        storageFoodItems: 'عناصر الطعام',
        backups: 'النسخ الاحتياطية',
        exportImport: 'تصدير/استيراد',
        storageExportData: 'تصدير البيانات',
        storageImportData: 'استيراد البيانات',
        importing: 'جاري الاستيراد...',
        backupManagement: 'إدارة النسخ الاحتياطية',
        createBackup: 'إنشاء نسخة احتياطية',
        clearAllData: 'مسح جميع البيانات',
        availableBackups: 'النسخ الاحتياطية المتاحة',
        storageItems: 'العناصر',
        storageRestore: 'استعادة',
        storageDelete: 'حذف',
        items: 'العناصر'
    }
};

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'en';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'ar' : 'en');
    };

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};
